### ISSUE TITLE
2021年の山の日が誤っている

### ISSUE THREAD

**Issue by newcre** [77web/Japanese.Holiday#30]
2021年の山の日は8/8ですが、 2021.yml では 2021-08-11 と定義されている(2022年の値)為、誤った挙動を行っているようです。

**Comment by newcre** [comment]
すみません、確認が不足していました。
オリンピックの特措法のせいでそれにまつわる祝日が全てずれてしまっているようです。
以下内閣府ホームページからの引用です。

---

令和３年（２０２１年）の祝日について
令和３年（2021年）に限り、「海の日」は7月22日に、「スポーツの日」は7月23日に、「山の日」は8月8日(※）になります。

**Comment by 77web** [comment]
@newcre 
ご報告ありがとうございます。
無事に参議院通過したようですので、折を見て対応したいと思います。
平日は仕事がある関係で週末になってしまいそうです :bow:

**Comment by newcre** [comment]
迅速なご回答ありがとうございます
ご対応よろしくお願いします🙇‍♂️
